- name: Install PHP and dependencies
  apt: name={{item}} state=present
  with_items:
    - php5-fpm
    - php5-cli
    - php5-intl
    - php5-mysql
    - php5-curl
  notify: Restart PHP-FPM
  
- name: Configure PHP timezone
  command: sed -i "s/;date.timezone =/date.timezone = Europe\/Paris/g" /etc/php5/fpm/php.ini /etc/php5/cli/php.ini