- name: Install PhpMyAdmin
  apt: name=phpmyadmin state=present
  
- name: Configure PhpMyAdmin
  template:
    src: phpmyadmin.config.php.j2
    dest: /etc/phpmyadmin/conf.d/config.php
    owner: www-data
  
- name: Configure site
  template:
    src: phpmyadmin.j2
    dest: /etc/nginx/sites-available/phpmyadmin
    
- name: Active site
  command: ln -sf /etc/nginx/sites-available/phpmyadmin /etc/nginx/sites-enabled/phpmyadmin
  notify:
    - Restart nginx